# Generated by Django 3.2.16 on 2023-10-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaApp', '0003_auto_20231013_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
