# Generated by Django 3.2.16 on 2023-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaApp', '0004_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_base64',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
