# Generated by Django 3.2.16 on 2023-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaApp', '0005_auto_20231015_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_base64',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_tipo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
