# Generated by Django 3.2.16 on 2023-10-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformaApp', '0009_alter_documento_archivo_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
    ]
